- platform: template
  sensors:
    mainfloor_movement:
      friendly_name: Rörelse bottenvåning
      device_class: occupancy
      value_template: >-
        {{ is_state('binary_sensor.rorelsesensor_hallen_occupancy', 'on')
            or is_state('binary_sensor.motion_hallen', 'on') }}
