- platform: command_line
  name: ps4
  command: /config/ps4_sensor.py ps4
  device_class: connectivity
  scan_interval: 5

- platform: template
  sensors:
    brandlarmet:
        friendly_name: Brandlarm
        value_template: "{{ is_state('sensor.brandvarnare_2_sensor_status', 'Panic') }}"
        device_class: smoke
        delay_off:
          seconds: 30
    washing_machine:
        friendly_name: "Tvättmaskinen"
        delay_off:
          minutes: 1
        value_template: >-
          {{ states('sensor.washing_machine_switch_power')|float > 5 }}

- platform: mqtt
  name: basement_entry
  state_topic: "emqtt/noreplypeers.se"
  device_class: motion

- platform: mqtt
  name: mainfloor
  state_topic: "emqtt/camera_mainfloorno.where"
  device_class: motion