homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 19
  unit_system: metric
  time_zone: Europe/Stockholm
  external_url: !secret base_url
  customize: !include customizations.yaml
  auth_mfa_modules:
    - type: totp
frontend:
config:
system_health:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 192.168.0.0/16

discovery:
conversation:
history:
logbook:
sun:
wake_on_lan:
default_config:

tts:
  platform: google_translate
  language: "sv"

google_assistant:
  project_id: !secret google_project_id
  service_account: !include google_service_account.json
  secure_devices_pin: !secret google_secure_device_pin
  report_state: true
  exposed_domains:
    - switch
    - light
    - lock
    - media_player
    - input_boolean
    - sensor

logger:
  default: warning
  logs:
    homeassistant.components.withings: critical
    #homeassistant.components.webhook: debug
    #homeassistant.components.zwave: debug
    #homeassistant.components.sensor.netatmo: debug
    #pydeconz: debug
    #homeassistant.components.deconz: debug

mqtt:
  broker: !secret mqtt_broker

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id
      - !secret telegram_par_chat_id
      - !secret telegram_malena_chat_id

alarm_control_panel:
  - platform: manual

withings:
  client_id: !secret withings_client_id
  client_secret: !secret withings_secret_id

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

influxdb: !include influxdb.yaml
group: !include_dir_merge_named group/
automation: !include_dir_merge_list automation/
media_player: !include media_players.yaml
binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
notify: !include notifiers.yaml
script: !include scripts.yaml
light: !include lights.yaml
input_boolean: !include input_boolean.yaml
timer: !include timers.yaml
camera: !include cameras.yaml
input_text: !include input_text.yaml
input_datetime: !include input_datetime.yaml
