homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 19
  unit_system: metric
  time_zone: Europe/Stockholm
  external_url: !secret base_url
  customize: !include customizations.yaml
  auth_mfa_modules:
    - type: totp
frontend:
config:
system_health:
recorder:
  db_url: !secret hass_db_string
  purge_keep_days: 10
  exclude:
    domains:
      - automation

updater:
  include_used_components: true

discovery:
conversation:
history:
logbook:
sun:
wake_on_lan:
default_config:

tts:
  platform: google_translate
  language: 'sv'

netatmo:
  client_id: !secret netatmo_api
  client_secret: !secret netatmo_api_secret

verisure:
  username: !secret verisure_user
  password: !secret verisure_password
  alarm: 0
  hygrometers: 0
  smartplugs: 0
  thermometers: 0
  mouse: 0
  door_window: 0
  code_digits: 6
  default_lock_code: !secret verisure_door_pin

google_assistant:
  project_id: !secret google_project_id
  service_account: !include google_service_account.json
  secure_devices_pin: !secret google_secure_device_pin
  report_state: true
  exposed_domains:
    - switch
    - light
    - lock
    - media_player
    - input_boolean
    - sensor

logger:
  default: warning
  logs:
    homeassistant.components.withings: critical
    #homeassistant.components.webhook: debug
    #homeassistant.components.rfxtrx: debug
    #homeassistant.components.zwave: debug
    #homeassistant.components.sensor.netatmo: debug
    #pydeconz: debug
    #homeassistant.components.deconz: debug

mqtt:
  broker: !secret mqtt_broker

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A11I6JAE-if00-port0
  devices:
    0820031eb5a3000670:
      fire_event: True


zwave:
  usb_path: /dev/serial/by-id/usb-0658_0200-if00
  debug: True
  device_config_glob:
    "sensor.dimmer_*_alarm_level":
      ignored: true
    "sensor.dimmer_*_heat":
      ignored: true
    "sensor.dimmer_*_alarm_type":
      ignored: true
    "sensor.dimmer_*_exporting":
      ignored: true
    "sensor.dimmer_*_system":
      ignored: true
    "sensor.dimmer_*_power_management":
      ignored: true
    "sensor.dimmer_*_sourcenodeid":
      ignored: true
    "sensor.baksidadorr_*":
      ignored: true

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id
      - !secret telegram_par_chat_id
      - !secret telegram_malena_chat_id


alarm_control_panel:
  - platform: manual

withings:
  client_id: !secret withings_client_id
  client_secret: !secret withings_secret_id

influxdb: !include influxdb.yaml
group: !include_dir_merge_named group/
automation: !include_dir_merge_list automation/
media_player: !include media_players.yaml
binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
notify: !include notifiers.yaml
script: !include scripts.yaml
light: !include lights.yaml
input_boolean: !include input_boolean.yaml
timer: !include timers.yaml
camera: !include cameras.yaml
input_text: !include input_text.yaml
