homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 19
  unit_system: metric
  time_zone: Europe/Stockholm
  language: sv
  external_url: !secret base_url
  auth_mfa_modules:
    - type: totp
  country: SE
frontend:
config:
system_health:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 192.168.0.0/16
    - 172.17.0.0/16

conversation:
history:
logbook:
sun:
wake_on_lan:
default_config:

google_assistant:
  project_id: !secret google_project_id
  service_account: !include google_service_account.json
  secure_devices_pin: !secret google_secure_device_pin
  report_state: true
  exposed_domains:
    - switch
    - light
    - lock
    - media_player
    - input_boolean
    - sensor
    - alarm_control_panel
    - cover

logger:
  default: info

alarm_control_panel:
  - platform: manual
    code_arm_required: false

prometheus:

automation: !include_dir_merge_list automation/
media_player: !include media_players.yaml
binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
notify: !include notifiers.yaml
script: !include scripts.yaml
light: !include lights.yaml
input_boolean: !include input_boolean.yaml
timer: !include timers.yaml
camera: !include cameras.yaml
input_text: !include input_text.yaml
input_datetime: !include input_datetime.yaml
mqtt: !include mqtt.yaml
