- name: Pushover
  platform: pushover
  api_key: !secret hass_pushover_api_key
  user_key: !secret pushover_user_key

- platform: html5
  name: html5
  vapid_pub_key: !secret vapid_pub_key
  vapid_prv_key: !secret vapid_prv_key
  vapid_email: !secret vapid_email

- name: telegram
  platform: telegram
  chat_id: !secret telegram_chat_id
