- platform: cert_expiry
  host: peers.se

- platform: template
  sensors:
    kamera_kallare:
      friendly_name: "Kamera källare"
      value_template: "{{ 'Online' if is_state('device_tracker.kamera_kallare', 'home') else 'Offline' }}"
    washing_machine:
      friendly_name: "Tvättmaskinen"
      value_template: >-
        {% if states('sensor.telldus_socket_and_energy_meter_electric_consumption_w')| float > 5 %}
          on
        {% elif states('sensor.telldus_socket_and_energy_meter_electric_consumption_w')| float > 0.0 %}
          standby
        {% elif is_state('sensor.telldus_socket_and_energy_meter_electric_consumption_w', '0.0') %}
          off
        {% endif %}
