- platform: template
  sensors:
    washing_machine:
      friendly_name: "Tvättmaskinen"
      value_template: >-
        {% if states('sensor.strombrytare_tvattmaskin_electric_consumption_w')| float(0.0) > 5 %}
          on
        {% elif states('sensor.strombrytare_tvattmaskin_electric_consumption_w')| float(0.0) > 0.0 %}
          standby
        {% elif is_state('sensor.strombrytare_tvattmaskin_electric_consumption_w', '0.0') %}
          off
        {% endif %}
