- platform: netatmo
  station: !secret netatmo_station
  modules:
    - Utomhus
    - Badrum källare
    - Regnmätare
    - Barnrummet
    - Vardagsrummet

- platform: rfxtrx
  devices:
    0820031eb5a3000670:
      name: brandvarnare_2
      fire_event: True

- platform: cert_expiry
  host: peers.se

- platform: template
  sensors:
    ir_gw_basement:
      friendly_name: 'IR-brygga'
      value_template: "{{ 'Online' if is_state('device_tracker.ir_gw_1', 'home') else 'Offline' }}"
    kamera_kallare:
      friendly_name: 'Kamera källare'
      value_template: "{{ 'Online' if is_state('device_tracker.kamera_kallare', 'home') else 'Offline' }}"
    baksida_dorr:
      friendly_name: 'Baksida dörr status'
      value_template: >-
          {% if is_state('binary_sensor.baksidadorr_sensor', 'on') %}
            Öppen
          {% else %}
            Stängd
          {% endif %}
