- platform: netatmo
  station: !secret netatmo_station
  modules:
    Utomhus:
      - temperature
      - humidity
      - battery_vp
      - rf_status
    Badrum källare:
      - temperature
      - humidity
      - co2
      - battery_vp
      - rf_status
    Regnmätare:
      - rain
      - sum_rain_1
      - sum_rain_24
      - battery_vp
      - rf_status
    Barnrummet:
      - temperature
      - humidity
      - co2
      - noise
    Vardagsrummet:
      - temperature
      - humidity
      - co2
      - battery_vp
      - rf_status

- platform: rfxtrx
  devices:
    0820031eb5a3000670:
      name: brandvarnare_2
      fire_event: True

- platform: cert_expiry
  host: peers.se

- platform: wunderground
  api_key: !secret wunderground_api_key
  monitored_conditions:
    - temp_high_record_c
    - temp_high_1d_c
    - temp_c
    - temp_low_1d_c
    - temp_low_record_c
    - precip_1d
    - precip_1d_mm
    - wind_kph
    - wind_1d_kph
    - alerts
    - UV
    - weather_1d_metric

- platform: template
  sensors:
    ir_gw_basement:
      friendly_name: 'IR-brygga'
      value_template: "{{ 'Online' if is_state('device_tracker.ir_gw_1', 'home') else 'Offline' }}"
    kamera_kallare:
      friendly_name: 'Kamera källare'
      value_template: "{{ 'Online' if is_state('device_tracker.kamera_kallare', 'home') else 'Offline' }}"
    baksida_dorr:
      friendly_name: 'Baksida dörr status'
      value_template: >-
          {% if is_state('binary_sensor.sensor', 'on') %}
            Öppen
          {% else %}
            Stängd
          {% endif %}

- platform: transmission
  host: localhost
  username: !secret transmission_user
  password: !secret transmission_password
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
    - 'active_torrents'
