- platform: netatmo
  station: !secret netatmo_station
  modules:
    Utomhus:
      - temperature
      - humidity
      - battery_vp
      - rf_status
    Badrum k채llare:
      - temperature
      - humidity
      - co2
      - battery_vp
      - rf_status
    Regnm채tare:
      - rain
      - sum_rain_1
      - sum_rain_24
      - battery_vp
      - rf_status
    Barnrummet:
      - temperature
      - humidity
      - co2
      - noise
    Vardagsrummet:
      - temperature
      - humidity
      - co2
      - battery_vp
      - rf_status

- platform: rfxtrx
  devices:
    0820031eb5a3000670:
      name: brandvarnare_2
      fire_event: True

- platform: cert_expiry
  host: peers.se

- platform: wunderground
  api_key: !secret wunderground_api_key
  monitored_conditions:
    - temp_high_record_c
    - temp_high_1d_c
    - temp_c
    - temp_low_1d_c
    - temp_low_record_c
    - precip_1d
    - precip_1d_mm
    - wind_kph
    - wind_1d_kph
    - alerts
    - UV
    - weather_1d_metric

- platform: template
  sensors:
    ir_gw_basement:
      friendly_name: 'IR-brygga'
      value_template: "{{ 'Online' if is_state('device_tracker.ir_gw_1', 'home') else 'Offline' }}"
    kamera_kallare:
      friendly_name: 'Kamera k채llare'
      value_template: "{{ 'Online' if is_state('device_tracker.kamera_kallare', 'home') else 'Offline' }}"
    netatmopersonalweatherstatio:
      friendly_name: 'Netatmo v채derstation'
      value_template: "{{ 'Online' if is_state('device_tracker.netatmopersonalweatherstatio', 'home') else 'Offline' }}"
