- platform: broadlink
  host: 192.168.7.119
  mac: '34:EA:34:40:84:CE'
  friendly_name: RMMini3_källare
  switches:
    projector:
      friendly_name: Projector
      command_on: 'JgDYAAABJpQSNxI4ERUQFBEVEBUQFRA4ETgSFBE4ERQROBEUETgTEhEVEBQRFBITETgSExMTETgROBE4EjcSOBEUETgROBEUEQAFPgABJZQSOBE4ERUQFRAUERUQFBE4EjcSExI4ERUQOBEUETgSExITERURFBEUETgRFRAVEDgROBE4EjgSNxEVEDgROBMSEgAFPAABJpQSNxI3ExMRFRAUERQRFRA4ETgRFBI3EhQROBEUETgRFRAVEBUQFRAUEjcTEhITEjgROBE4ETgSNxMTETgROBEUEQANBQ=='
      command_off: 'JgDYAAABJpQSNxI3EhMSFBEUEhMRFBI3ETgTEhM2EhMTNhIUETgRFBI3ExIRFBEUETgSExITEzcRFBE4ETgROBEUEjcSOBITEQAFPQABJpQROBI4ERQRFBEUERQRFRA4ETgSExI4ERMSOBEUETgRFBE4EhMTEhEUETgSFBEUETgRFBE4ETgSNxIUETgSNxITEQAFPQABJpQTNhE4ERQRFBIUERMSExI4ETgRFBE4EhMSNxITEjgRFBE4ERQRFBEUETgSExEUETkRFBE4ETgROBEUETgSOBEVEAANBQ=='
