---

- alias: "Tänd lampa i biorummet"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.philips_hue_1_motion
      to: "on"
    - platform: state
      entity_id:
        - media_player.tv_kallare
        - media_player.marantz_sr5007
        - media_player.shield_cast
      to:
        - "off"
        - "paused"
  action:
    - service: light.turn_on
      data:
        entity_id: light.dimmer_1_level
        transition: 5
        brightness: 120

- alias: "Släck lampa i biorummet"
  trigger:
    - platform: state
      entity_id:
        - media_player.playstation_4
        - media_player.shield_cast
      to:
        - "playing"
  action:
    - service: light.turn_off
      data:
        entity_id: light.dimmer_1_level
        transition: 5

- alias: "Stäng av hembio"
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.the_button
      scene_id: 1
      scene_data: 7800
  action:
    - service: light.turn_on
      data:
        entity_id: light.dimmer_1_level
        transition: 5
        brightness: 120
    - service: media_player.turn_off
      entity_id: media_player.tv_kallare
