---
- alias: 'Marantz auto on'
  trigger:
    - platform: state
      entity_id: media_player.kodi
      from: 'off'
      to: 'idle'
    - platform: state
      entity_id: media_player.kallaren
      to: 'playing'
    - platform: state
      entity_id: media_player.playstation_4
      to: 'idle'
  action:
    - service: media_player.turn_on
      entity_id: media_player.marantz_sr5007
    - service: media_player.select_source
      data_template:
        entity_id: media_player.marantz_sr5007
        source: >
          {% if trigger.entity_id == 'media_player.kodi' %}
          MEDIA PLAYER
          {% elif trigger.entity_id == 'media_player.kallaren' %}
          CBL/SAT
          {% elif trigger.entity_id == 'media_player.playstation_4' %}
          GAME
          {% endif %}
    - service: switch.turn_on
      entity_id: switch.projector

- alias: 'Marantz auto off'
  trigger:
    - platform: state
      entity_id:
        - media_player.kodi
        - media_player.kallaren
      to: 'off'
      for:
        minutes: 1
    - platform: state
      entity_id: media_player.playstation_4
      to: 'standby'
      for:
        minutes: 1
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id:
          - media_player.kodi
          - media_player.kallaren
        state: 'off'
      - condition: state
        entity_id: media_player.playstation_4
        state: 'standby'
  action:
    - service: homeassistant.turn_off
      entity_id: media_player.marantz_sr5007
    - service: switch.turn_off
      entity_id: switch.projector

- alias: "Tänd lampa när kodi pausar"
  trigger:
    - platform: state
      entity_id: media_player.kodi
      to: 'paused'
  action:
    - service: light.turn_on
      data:
        entity_id: light.dimmer_1_level
        brightness: 120
        transition: 5

- alias: "Släck lampa när kodi spelar"
  trigger:
    - platform: state
      entity_id: media_player.kodi
      to: 'playing'
  action:
    - service: light.turn_off
      data:
        entity_id: light.dimmer_1_level
        transition: 5

- alias: "Släck lampa när projector är igång"
  trigger:
    - platform: state
      entity_id: switch.projector
      to: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.dimmer_1_level
        transition: 60

- alias: "Tänd lampa i biorummet"
  trigger:
    - platform: state
      entity_id: switch.projector
      to: 'off'
    - platform: state
      entity_id:
        - binary_sensor.philips_hue_1_motion
      to: "on"
  condition:
    - condition: state
      entity_id:
        - switch.projector
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.dimmer_1_level
        transition: 5
        brightness: 120

- alias: "Starta hembio"
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.the_button
      scene_id: 1
      scene_data: 7680
  action:
    - service: media_player.turn_on
      entity_id: media_player.kodi
    - service: media_player.turn_on
      entity_id: media_player.marantz_sr5007
    - service: switch.turn_on
      entity_id: switch.projector

- alias: "Stäng av hembio"
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.the_button
      scene_id: 1
      scene_data: 7800
  action:
    - service: switch.turn_off
      entity_id: switch.projector
    - service: light.turn_on
      data:
        entity_id: light.dimmer_1_level
        transition: 5
        brightness: 120
    - service: media_player.turn_off
      entity_id: media_player.marantz_sr5007
    - service: media_player.turn_off
      entity_id: media_player.kodi

- alias: "Pausa/starta uppspelning med knapp"
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.the_button
      scene_id: 1
      scene_data: 7860
  action:
    - service: media_player.media_play_pause
      entity_id: media_player.kodi
    - delay:
        seconds: 5
    - service: notify.kodi
      data:
        message: "Aktiverad av röda knappen"
        data:
          icon: "info"
          displaytime: 10000
