---
- alias: "Släck lampa i biorummet"
  trigger:
    - platform: state
      entity_id:
        - media_player.playstation_4
        - media_player.basement_media
      to:
        - "playing"
  action:
    - service: light.turn_off
      data:
        entity_id: light.dimmer_2
        transition: 5

- alias: "Tänd lampa i biorummet"
  trigger:
    - platform: state
      entity_id:
        - media_player.playstation_4
        - media_player.basement_media
        - media_player.marantz_sr5007
      to:
        - "paused"
        - "standby"
        - "off"
  action:
    - service: light.turn_on
      data:
        entity_id: light.dimmer_2
        transition: 5
        brightness: 120
