---
- alias: 'Marantz auto on'
  trigger:
    - platform: state
      entity_id: media_player.playstation_4
      to:
        - 'idle'
        - 'playing'
  action:
    - service: media_player.turn_on
      entity_id: media_player.marantz_sr5007
    - service: media_player.select_source
      data_template:
        entity_id: media_player.marantz_sr5007
        source: >
          {% if trigger.entity_id == 'media_player.playstation_4' %}
          GAME
          {% endif %}

- alias: 'Marantz auto off'
  trigger:
    - platform: state
      entity_id: media_player.playstation_4
      to: 'standby'
      for:
        minutes: 1
  action:
    - service: media_player.turn_off
      entity_id: media_player.marantz_sr5007

- alias: "Tänd lampa i biorummet"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.philips_hue_1_motion
      to: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.dimmer_1_level
        transition: 5
        brightness: 120

- alias: "Starta hembio"
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.the_button
      scene_id: 1
      scene_data: 7680
  action:
    - service: media_player.turn_on
      entity_id: media_player.marantz_sr5007

- alias: "Stäng av hembio"
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.the_button
      scene_id: 1
      scene_data: 7800
  action:
    - service: light.turn_on
      data:
        entity_id: light.dimmer_1_level
        transition: 5
        brightness: 120
    - service: media_player.turn_off
      entity_id: media_player.marantz_sr5007
