- alias: 'lock notify action'
  trigger:
    - platform: event
      event_type: html5_notification.clicked
      event_data:
        action: lock_door
  action:
    - service: script.lock_door

- alias: 'Lås upp notis action'
  trigger:
    - platform: event
      event_type: html5_notification.clicked
      event_data:
        action: unlock_door 
  action:
    - service: script.unlock_door

- alias: "Släck lampor när solen går upp"
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: light.turn_off
      entity_id: light.lampa_ytterdorren
    - service: switch.turn_off
      entity_id: switch.strombrytare_1
    - service: switch.turn_off
      entity_id: switch.strombrytare_2
    - service: switch.turn_off
      entity_id: switch.ikea_switch_2

- alias: "Tänd lampor när solen går ned"
  trigger:
    platform: sun
    event: sunset
  action:
    - service: light.turn_on
      entity_id: light.lampa_ytterdorren
    - service: switch.turn_on
      entity_id: switch.strombrytare_1
    - service: switch.turn_on
      entity_id: switch.strombrytare_2
    - service: switch.turn_on
      entity_id: switch.ikea_switch_2

- alias: 'Telegram washing response done'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/washing_done'
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'OK'
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: []
    - service: notify.telegram
      data:
        message: "Ok, vad bra."

- alias: 'Telegram washing responser reminder'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/washing_reminder'
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'OK'
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: []
    - service: notify.telegram
      data:
        message: "Okej, påminner igen om 20 min"
    - service: timer.start
      entity_id: timer.laundry_reminder

- alias: 'Aktivera sovläge'
  trigger:
    platform: state
    entity_id: input_boolean.all_asleep
    to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: group.indoor_lights

- alias: "Reset smoke alarm"
  trigger:
    platform: state
    entity_id: sensor.brandvarnare_2_sensor_status
    to: 'on'
    for:
      minutes: 5
  action:
    - service: homeassistant.turn_off
      entity_id: binary_sensor.brandlarmet

- alias: "tvätten påminnelse"
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.laundry_reminder
  action:
    - service: automation.trigger
      entity_id: automation.tvatten_klar

- alias: 'Släcker lampor'
  trigger:
    - platform: state
      entity_id: group.device_tracker
      from: 'home'
      to: 'not_home'
      for:
        minutes: 20
  action:
    - service: light.turn_off
      entity_id: light.dimmer_1_level, light.dimmer_2_level