- alias: "Släck lampor när solen går upp"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    above: -2.0
  action:
    - service: light.turn_off
      entity_id: light.lampa_ytterdorren
    - service: switch.turn_off
      entity_id: switch.strombrytare_1
    - service: switch.turn_off
      entity_id: switch.strombrytare_2
    - service: switch.turn_off
      entity_id: switch.ikea_switch_2

- alias: "Tänd lampor när solen går ned"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: -2.0
  action:
    - service: light.turn_on
      entity_id: light.lampa_ytterdorren
    - service: switch.turn_on
      entity_id: switch.strombrytare_1
    - service: switch.turn_on
      entity_id: switch.strombrytare_2
    - service: switch.turn_on
      entity_id: switch.ikea_switch_2

- alias: 'Telegram washing responser reminder'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/washing_reminder'
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'OK'
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: []
    - service: notify.telegram
      data:
        message: "Okej, påminner igen om 20 min"
    - service: timer.start
      entity_id: timer.laundry_reminder

- alias: 'Aktivera sovläge'
  trigger:
    platform: state
    entity_id: input_boolean.all_asleep
    to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: group.indoor_lights
    - service: lock.lock
      entity_id: lock.ytterdorren

- alias: "Reset smoke alarm"
  trigger:
    platform: state
    entity_id: sensor.brandvarnare_2_sensor_status
    to: 'on'
    for:
      minutes: 5
  action:
    - service: homeassistant.turn_off
      entity_id: binary_sensor.brandlarmet

- alias: "tvätten påminnelse"
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.laundry_reminder
  action:
    - service: automation.trigger
      entity_id: automation.tvatten_klar

- alias: 'Släcker lampor'
  trigger:
    - platform: state
      entity_id: group.family
      to: 'not_home'
      for:
        minutes: 5
  action:
    - service: light.turn_off
      entity_id: light.dimmer_1_level

- alias: 'Aktivera semesterläge'
  trigger:
    platform: state
    entity_id: input_boolean.vacation_mode
    to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: group.vacation_toggle
    - service: notify.telegram
      data_template:
        message: |
          Semesterläge aktiverat!
          Glöm inte:
            * Slänga sopor
            * Låsa källardörren ordentligt
            * Stänga fönster
            * Ta med packningen :)

- alias: 'Deaktivera semesterläge'
  trigger:
    platform: state
    entity_id: input_boolean.vacation_mode
    to: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: group.vacation_toggle
    - service: notify.telegram
      data_template:
        message: "Semesterläge deaktiverat!"

- alias: 'Toggle sleep mode'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: tradfri_remote_control
      event: 1002
  action:
    service: input_boolean.toggle
    entity_id: input_boolean.all_asleep

- alias: 'Aktiverar gästläge'
  trigger:
    platform: state
    entity_id: input_boolean.guest_mode
    to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: group.guest_toggle
    - service: notify.telegram
      data:
        message: "Gästläget aktiverat"

- alias: 'Deaktivera gästläge'
  trigger:
    platform: state
    entity_id: input_boolean.guest_mode
    to: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: group.guest_toggle
    - service: notify.telegram
      data:
        message: "Gästläget deaktiverat"