- alias: "Släck lampor när solen går upp"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    above: -2.0
  action:
    - service: light.turn_off
      entity_id: light.utomhusbelysning
    - service: light.turn_off
      entity_id: light.trappa_1

- alias: "Tänd lampor när solen går ned"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: -2.0
  action:
    - service: light.turn_on
      entity_id: light.utomhusbelysning
    - service: light.turn_on
      entity_id: light.trappa_1
      data:
        brightness: 1

- alias: "Telegram washing responser reminder"
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: "/washing_reminder"
  action:
    - service: telegram_bot.answer_callback_query
      data:
        callback_query_id: "{{ trigger.event.data.id }}"
        message: "OK"
    - service: telegram_bot.edit_replymarkup
      data:
        message_id: "{{ trigger.event.data.message.message_id }}"
        chat_id: "{{ trigger.event.data.chat_id }}"
        inline_keyboard: []
    - service: notify.telegram
      data:
        message: "Okej, påminner igen om 20 min"
    - service: timer.start
      entity_id: timer.laundry_reminder

- alias: "tvätten påminnelse"
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.laundry_reminder
  action:
    - service: automation.trigger
      entity_id: automation.tvatten_klar

- alias: "Släcker lampor när ingen är hemma"
  trigger:
    - platform: state
      entity_id: zone.home
      to: "0"
  action:
    - service: light.turn_off
      entity_id:
        - light.dimmer_2_3
        - light.dimmer_2

- alias: "Aktivera semesterläge"
  trigger:
    - platform: state
      entity_id: input_boolean.vacation_mode
      to: "on"
  action:
    - service: homeassistant.turn_off
      entity_id: group.vacation_toggle
    - service: notify.telegram
      data:
        message: |
          Semesterläge aktiverat!
          ```
            * Slänga sopor
            * Låsa källardörren ordentligt
            * Stänga fönster
            * Ta med packningen :)
            * Aktivera larmet
          ```

- alias: "Deaktivera semesterläge"
  trigger:
    platform: state
    entity_id: input_boolean.vacation_mode
    to: "off"
  action:
    - service: homeassistant.turn_on
      entity_id: group.vacation_toggle
    - service: notify.telegram
      data:
        message: "Semesterläge deaktiverat!"

- alias: "Slå på/av sömnläge"
  trigger:
    - platform: device
      domain: mqtt
      device_id: be97d2becd2837f0e41a135762554abe
      type: action
      subtype: toggle
      discovery_id: 0xd0cf5efffef942f0 action_toggle
  action:
    service: input_boolean.toggle
    entity_id: input_boolean.all_asleep

- alias: Update OpenUV every 20 minutes while the sun is at least 10 degrees above the horizon
  trigger:
    platform: time_pattern
    minutes: "/20"
  condition:
    condition: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    above: 10
  action:
    service: openuv.update_uv_index_data

- alias: "Slå på nattläge"
  trigger:
    platform: state
    entity_id:
      - binary_sensor.par_asleep
    to: "on"
  condition:
    - condition: state
      entity_id: person.par
      state: "home"
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.all_asleep

- alias: "Slå av nattläge"
  trigger:
    platform: state
    entity_id:
      - binary_sensor.par_asleep
    from: "on"
    to: "off"
  condition:
    - condition: state
      entity_id: person.par
      state: "home"
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.all_asleep

- id: automation_guest_toggle
  alias: "Slå på/av automationer under gästläge"
  description: "Automationer som inte ska vara på när vi har gäster och inte är hemma"
  variables:
    entities:
      - automation.aktivera_larmet
      - automation.baksida_dorr_oppen
      - automation.slacker_lampor_nar_ingen_ar_hemma
  trigger:
    - platform: state
      entity_id: input_boolean.guest_mode
      id: guest_mode_on
      to: "on"
    - platform: state
      entity_id: input_boolean.guest_mode
      id: guest_mode_off
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: guest_mode_on
          sequence:
            - service: automation.turn_off
              data: {}
              target:
                entity_id: "{{ entities }}"
        - conditions:
            - condition: trigger
              id: guest_mode_off
          sequence:
            - service: automation.turn_on
              data: {}
              target:
                entity_id: "{{ entities }}"
      default: []
  mode: single
