- alias: 'lock notify action'
  trigger:
    - platform: event
      event_type: html5_notification.clicked
      event_data:
        action: lock_door
  action:
    - service: script.lock_door

- alias: 'Lås upp notis action'
  trigger:
    - platform: event
      event_type: html5_notification.clicked
      event_data:
        action: unlock_door 
  action:
    - service: script.unlock_door

- alias: "Släck lampor när solen går upp"
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: light.turn_off
      entity_id: light.lampa_ytterdorren
    - service: switch.turn_off
      entity_id: switch.strombrytare_1
    - service: switch.turn_off
      entity_id: switch.strombrytare_2
    - service: switch.turn_off
      entity_id: switch.strombrytare_5

- alias: "Tänd lampor när solen går ned"
  trigger:
    platform: sun
    event: sunset
  action:
    - service: light.turn_on
      entity_id: light.lampa_ytterdorren
    - service: switch.turn_on
      entity_id: switch.strombrytare_1
    - service: switch.turn_on
      entity_id: switch.strombrytare_2
    - service: switch.turn_on
      entity_id: switch.strombrytare_5
    - service: switch.turn_on
      entity_id: switch.strombrytare_3


- alias: 'Telegram response no'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/nej'
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'OK'
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: []
    - service: notify.telegram
      data:
        message: "Okej, tänder inga lampor"

- alias: 'Telegram response yes'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/yes'
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'OK'
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: []
    - service: notify.telegram
      data:
        message: "Okej, tänder lampor"
    - service: switch.turn_on
      entity_id: switch.strombrytare_5
    - service: switch.turn_off
      entity_id: switch.strombrytare_3
    - service: light.turn_on
      data:
        entity_id: light.dimmer_2_level
        brightness: 120


- alias: 'Telegram response sleep no'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/no_sleep'
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'OK'
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: []
    - service: notify.telegram
      data:
        message: "Okej, släcker inga lampor"

- alias: 'Telegram response sleep yes'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/yes_sleep'
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'OK'
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: []
    - service: notify.telegram
      data:
        message: "Okej, släcker lampor"
    - service: homeassistant.turn_off
      entity_id: group.indoor_lights


- alias: 'Sov gott'
  trigger:
    platform: state
    entity_id: input_boolean.all_asleep
    to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: group.indoor_lights
