- id: lights_secondary_toggle
  alias: "Släck/tänd lampor när solen går upp & ned"
  variables:
    entities:
      - light.utomhus
      - light.lampa_i_trappan_pa_overvaningen
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      above: -2.0
      id: "sun_up"
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      below: -2.0
      id: "sun_down"
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: "sun_up"
          sequence:
            - service: light.turn_off
              target:
                entity_id: "{{ entities }}"
        - conditions:
            - condition: trigger
              id: "sun_down"
          sequence:
            - service: light.turn_on
              data:
                brightness_pct: 30
                transition: 10
              target:
                entity_id: "{{ entities }}"
      default: []
  mode: single

- alias: "Semesterläge"
  trigger:
    - platform: state
      entity_id: input_boolean.vacation_mode
      to: "on"
      id: notify

    - platform: state
      entity_id: zone.home
      to: "0"
      for:
        hours: 24
      id: activate

    - platform: numeric_state
      entity_id: zone.home
      above: "0"
      for:
        hours: 1
      id: deactivate
  action:
    - alias: "Vacation mode choises"
      choose:
        - conditions:
            - condition: trigger
              id: notify
          sequence:
            - service: notify.telegram
              data:
                message: |
                  Semesterläge aktiverat!
                  ```
                    * Slänga sopor
                    * Låsa källardörren ordentligt
                    * Stänga fönster
                    * Ta med packningen :)
                    * Aktivera larmet
                  ```
        - conditions:
            - condition: trigger
              id: activate
          sequence:
            - service: input_boolean.turn_on
              target:
                entity_id: input_boolean.vacation_mode
        - conditions:
            - condition: trigger
              id: deactivate
            - condition: state
              entity_id: input_boolean.vacation_mode
              state: "on"
              for:
                hours: 24
          sequence:
            - service: input_boolean.turn_off
              target:
                entity_id: input_boolean.vacation_mode
      default: []

- alias: "Slå på nattläge"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.rorelsesensor_kallartrappen_occupancy
        - binary_sensor.rorelsesensor_overvaningen_occupancy
      from:
        - "on"
      to:
        - "off"
      for:
        hours: 1
  condition:
    - condition: numeric_state
      entity_id: zone.home
      above: "0"
    - condition: time
      after: "00:00:00"
      before: "07:00:00"
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.all_asleep

- alias: "Slå av nattläge"
  trigger:
    - platform: state
      entity_id: binary_sensor.rorelsesensor_overvaningen_occupancy
      from:
        - "off"
      to:
        - "on"
  condition:
    - condition: time
      after: "07:00:00"
      before: "11:00:00"
    - condition: state
      entity_id: input_boolean.all_asleep
      state: "on"
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.all_asleep

- id: automation_guest_toggle
  alias: "Slå på/av automationer under gästläge"
  description: "Automationer som inte ska vara på när vi har gäster och inte är hemma"
  variables:
    entities:
      - automation.aktivera_larmet
      - automation.baksida_dorr_oppen
      - automation.slacker_lampor_nar_ingen_ar_hemma
  trigger:
    - platform: state
      entity_id: input_boolean.guest_mode
      id: guest_mode_on
      to: "on"
    - platform: state
      entity_id: input_boolean.guest_mode
      id: guest_mode_off
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: guest_mode_on
          sequence:
            - service: automation.turn_off
              data: {}
              target:
                entity_id: "{{ entities }}"
        - conditions:
            - condition: trigger
              id: guest_mode_off
          sequence:
            - service: automation.turn_on
              data: {}
              target:
                entity_id: "{{ entities }}"
      default: []
  mode: single
