- id: lights_secondary_toggle
  alias: "Släck/tänd lampor när solen går upp & ned"
  variables:
    entities:
      - light.utomhus
      - light.lampa_i_trappan_pa_overvaningen
      - light.dimmer_vardagsrummet
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      above: -2.0
      id: "sun_up"
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      below: -2.0
      id: "sun_down"
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: "sun_up"
          sequence:
            - service: light.turn_off
              target:
                entity_id: "{{ entities }}"
        - conditions:
            - condition: trigger
              id: "sun_down"
          sequence:
            - service: light.turn_on
              target:
                entity_id: "{{ entities }}"
      default: []
  mode: single

- alias: "Aktivera semesterläge"
  trigger:
    - platform: state
      entity_id: input_boolean.vacation_mode
      to: "on"
  action:
    - service: notify.telegram
      data:
        message: |
          Semesterläge aktiverat!
          ```
            * Slänga sopor
            * Låsa källardörren ordentligt
            * Stänga fönster
            * Ta med packningen :)
            * Aktivera larmet
          ```

- alias: "Slå på nattläge"
  trigger:
    platform: state
    entity_id:
      - binary_sensor.par_asleep
    to: "on"
  condition:
    - condition: state
      entity_id: person.par
      state: "home"
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.all_asleep

- alias: "Slå av nattläge"
  trigger:
    platform: state
    entity_id:
      - binary_sensor.par_asleep
    to: "off"
  condition:
    - condition: state
      entity_id: person.par
      state: "home"
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.all_asleep

- id: automation_guest_toggle
  alias: "Slå på/av automationer under gästläge"
  description: "Automationer som inte ska vara på när vi har gäster och inte är hemma"
  variables:
    entities:
      - automation.aktivera_larmet
      - automation.baksida_dorr_oppen
      - automation.slacker_lampor_nar_ingen_ar_hemma
  trigger:
    - platform: state
      entity_id: input_boolean.guest_mode
      id: guest_mode_on
      to: "on"
    - platform: state
      entity_id: input_boolean.guest_mode
      id: guest_mode_off
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: guest_mode_on
          sequence:
            - service: automation.turn_off
              data: {}
              target:
                entity_id: "{{ entities }}"
        - conditions:
            - condition: trigger
              id: guest_mode_off
          sequence:
            - service: automation.turn_on
              data: {}
              target:
                entity_id: "{{ entities }}"
      default: []
  mode: single
