- alias: "Tänd hallen när dörren blir upplåst"
  trigger:
    - platform: state
      entity_id: lock.ytterdorren
      from: 'locked'
      to: 'unlocked'
  action:
    - service: light.turn_on
      data:
        entity_id: light.dimmer_2_level
        brightness: 120

- alias: 'Glömde låsa dörren notis'
  trigger:
    - platform: state
      entity_id: group.device_tracker
      from: 'home'
      to: 'not_home'
      for:
        minutes: 5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: lock.ytterdorren
        state: 'unlocked'
  action:
    - service: script.lock_door
    - service: notify.telegram
      data_template:
        title: 'Dörren låst'
        message: 'Jag låste dörren för ni är inte hemma längre'