- alias: "T채nd lampor bottenv책ning"
  trigger:
    - platform: state
      entity_id: binary_sensor.tradfri_motion_sensor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.tradfri_motion_sensor_2
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.dimmer_2_level
        brightness: 120
    - service: light.turn_on
      data:
        entity_id: light.kallartrappsbelysning
        brightness: 120

- alias: "Sl채ck lampor bottenv책ning"
  trigger:
    - platform: state
      entity_id: binary_sensor.tradfri_motion_sensor,binary_sensor.tradfri_motion_sensor_2
      to: 'off'
      for:
        seconds: 30
  action:
    - service: light.turn_off
      entity_id: light.dimmer_2_level
      data:
        transition: 10
    - service: light.turn_off
      entity_id: light.kallartrappsbelysning
      data:
        transition: 10