- alias: "Tänd hallen när dörren blir upplåst"
  trigger:
    - platform: state
      entity_id: lock.ytterdorren
      from: 'locked'
      to: 'unlocked'
  action:
    - service: light.turn_on
      data:
        entity_id: light.dimmer_2_level
        brightness: 120
    - service: script.flash_door_light
    - condition: or
      conditions:
        - condition: state
          entity_id: light.lampa_ytterdorren
          state: 'on'