- alias: "Tänd lampor hallen"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.tradfri_motion_sensor
        - binary_sensor.kallartrapp_rorelse
      to: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.dimmer_2_3
        brightness: 120

- alias: "dimra i hallen"
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.tradfri_motion_sensor
      to: "off"
  action:
    - service: light.turn_on
      target:
        entity_id: light.dimmer_2_3
      data:
        transition: 5
        brightness_pct: 20

- alias: "Släck lampor hallen"
  trigger:
    - platform: state
      entity_id: binary_sensor.tradfri_motion_sensor
      to: "off"
      for:
        minutes: 1
  action:
    - service: light.turn_off
      entity_id: light.dimmer_2_3

- alias: "Tänd lampor källartrapp"
  trigger:
    - platform: state
      entity_id: binary_sensor.kallartrapp_rorelse
      to: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.kallartrappsbelysning

- alias: "Släck lampor källartrapp"
  trigger:
    - platform: state
      entity_id: binary_sensor.kallartrapp_rorelse
      to: "off"
      for:
        minutes: 1
  action:
    - service: light.turn_off
      entity_id: light.kallartrappsbelysning

- alias: "Slå på/av barnen sover"
  mode: single
  trigger:
    - platform: device
      domain: mqtt
      device_id: 8362a880fabe0828688c53783efad326
      type: click
      subtype: single
      discovery_id: 0x00158d0002901693 click_single
  action:
    - service: input_boolean.toggle
      target:
        entity_id: input_boolean.kids_asleep
