- alias: "Tänd lampor hallen"
  trigger:
    - platform: state
      entity_id: binary_sensor.tradfri_motion_sensor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.tradfri_motion_sensor_2
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.dimmer_2_level
        brightness: 120

- alias: "Släck lampor hallen"
  trigger:
    - platform: state
      entity_id: binary_sensor.tradfri_motion_sensor
      to: 'off'
      for:
        minutes: 2
  action:
    - service: light.turn_off
      entity_id: light.dimmer_2_level

- alias: "Tänd lampor källartrapp"
  trigger:
    - platform: state
      entity_id: binary_sensor.tradfri_motion_sensor_2
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.kallartrappsbelysning

- alias: "Släck lampor källartrapp"
  trigger:
    - platform: state
      entity_id: binary_sensor.tradfri_motion_sensor_2
      to: 'off'
      for:
        minutes: 2
  action:
    - service: light.turn_off
      entity_id: light.kallartrappsbelysning