- id: lights_basement_stairs_toggle
  alias: "Tänd/släck lampor källartrapp"
  trigger:
    - platform: state
      entity_id: binary_sensor.rorelsesensor_kallartrappen_occupancy
      from: "on"
      to: "off"
      for:
        minutes: 1
      id: turn_off
    - type: motion
      platform: device
      device_id: 54c1cc3ec619dbc2ed3e18f0222124f1
      entity_id: binary_sensor.rorelsesensor_kallartrappen_occupancy
      domain: binary_sensor
      id: turn_on
  action:
    - alias: "Turn on/off basement stairs light"
      choose:
        - conditions:
            - condition: trigger
              id: turn_on
          sequence:
            - service: light.turn_on
              target:
                entity_id:
                  - light.kallartrapp
        - conditions:
            - condition: trigger
              id: turn_off
          sequence:
            - service: light.turn_off
              target:
                entity_id:
                  - light.kallartrapp

- alias: "Slå på/av barnenvaktsläge"
  mode: single
  trigger:
    - platform: mqtt
      topic: zigbee2mqtt/0x00158d0002901693/action
      payload: single
  action:
    - service: input_boolean.toggle
      target:
        entity_id: input_boolean.barnvaktslage

- id: lights_hallway_toggle
  alias: "Tänd/Släck lampor i hallen"
  mode: restart
  trigger:
    - platform: state
      entity_id:
        - lock.ytterdorren
      from: locked
      to: unlocked

    - platform: state
      entity_id:
        - binary_sensor.mainfloor_movement
      to: "on"
      id: turn_on

    - platform: state
      entity_id:
        - binary_sensor.mainfloor_movement
      to: "off"
      for:
        minutes: 2
      id: dim

    - platform: state
      entity_id:
        - binary_sensor.mainfloor_movement
      to: "off"
      for:
        minutes: 5
      id: turn_off
  action:
    - alias: "Control hallway lights"
      choose:
        - conditions:
            - condition: trigger
              id: turn_on
          sequence:
            - service: light.turn_on
              data:
                entity_id:
                  - light.dimmer_2
                brightness_pct: 100
        - conditions:
            - condition: trigger
              id: dim
          sequence:
            - service: light.turn_on
              data:
                entity_id:
                  - light.dimmer_2
                brightness_pct: 25
                transition: 10
        - conditions:
            - condition: trigger
              id: turn_off
          sequence:
            - service: light.turn_off
              target:
                entity_id:
                  - light.dimmer_2

- id: Light_mainfloor_painting
  alias: "Tänd/släck tavelljus"
  trigger:
    - platform: state
      entity_id: camera.uvc_g3_flex
      to: "recording"
      id: turn_on
    - platform: state
      entity_id: camera.uvc_g3_flex
      to: "idle"
      for:
        minutes: 30
      id: turn_off
  action:
    - alias: "Turn on/off painting light"
      choose:
        - conditions:
            - condition: trigger
              id: turn_on
          sequence:
            - service: light.turn_on
              target:
                entity_id:
                  - light.strombrytare_vardagsrummet
        - conditions:
            - condition: trigger
              id: turn_off
          sequence:
            - service: light.turn_off
              target:
                entity_id:
                  - light.strombrytare_vardagsrummet
