- alias: "Tänd lampor hallen"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.rorelsesensor_hallen_occupancy
        - binary_sensor.rorelsesensor_kallartrappen_occupancy
      to: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.dimmer_2_3
        brightness: 120

- alias: "dimra i hallen"
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.rorelsesensor_hallen_occupancy
      to: "off"
  action:
    - service: light.turn_on
      target:
        entity_id: light.dimmer_2_3
      data:
        transition: 5
        brightness_pct: 20

- alias: "Släck lampor hallen"
  trigger:
    - platform: state
      entity_id: binary_sensor.rorelsesensor_hallen_occupancy
      to: "off"
      for:
        minutes: 1
  action:
    - service: light.turn_off
      entity_id: light.dimmer_2_3

- id: lights_basement_stairs_toggle
  alias: "Tänd/släck lampor källartrapp"
  trigger:
    - platform: state
      entity_id: binary_sensor.rorelsesensor_kallartrappen_occupancy
      to: "off"
      for:
        minutes: 1
      id: turn_off
    - type: motion
      platform: device
      device_id: 54c1cc3ec619dbc2ed3e18f0222124f1
      entity_id: binary_sensor.rorelsesensor_kallartrappen_occupancy
      domain: binary_sensor
      id: turn_on
  action:
  - alias: "Turn on/off basement stairs light"
    choose:
    - conditions:
      - condition: trigger
        id: turn_on
      sequence:
        - service: light.turn_on
          target:
            entity_id:
              - light.kallartrapp
    - conditions:
      - condition: trigger
        id: turn_off
      sequence:
        - service: light.turn_off
          target:
            entity_id:
              - light.kallartrapp

- alias: "Slå på/av barnen sover"
  mode: single
  trigger:
    - platform: device
      domain: mqtt
      device_id: 8362a880fabe0828688c53783efad326
      type: click
      subtype: single
      discovery_id: 0x00158d0002901693 click_single
  action:
    - service: input_boolean.toggle
      target:
        entity_id: input_boolean.kids_asleep
