- alias: "Notifiera ifall dörren är upplåst när kodi spelar"
  trigger:
    - platform: state
      entity_id: media_player.kodi
      to: 'playing'
  condition:
    condition: state
    entity_id: lock.ytterdorren
    state: 'unlocked' 
  action:
    - service: notify.html5
      data:
        message: 'Dörren är upplåst. Du kanske vill låsa när du ska sitta i källaren'
        target: "Pär telefon"
        data:
          tag: 'forgot-lock'
          actions:
            - action: 'lock_door'
              title: 'Lås dörren'

- alias: "Brandlarmet notis"
  trigger:
    - platform: event
      event_type: signal_received
      event_data: {"entity_id": "sensor.brandvarnare_2_sensor_status"}
  action:
    - service: notify.html5
      data:
        message: 'Brandlarmet utlöst!'
    - service: notify.pushover
      data:
        message: 'Brandlarmet utlöst!'
    - service: notify.telegram
      data:
        message: "Verkar som brandlarmet har utlösts klockan {{ now().strftime('%H:%M') }}!"

- alias: "Rörelse i källaren"
  trigger:
    - platform: state
      entity_id: binary_sensor.basement_entry
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.device_tracker
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
  action:
    service: notify.telegram
    data:
      target: !secret telegram_par_chat_id
      message: 'Rörelse upptäckt i källaringången'

- alias: "Ny enhet hittad notis"
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    - service: notify.telegram
      data_template:
        target: !secret telegram_par_chat_id
        message: "Ny enhet spåras: {{ trigger.event.data }}"

- alias: "Enhet offline"
  trigger:
    platform: state
    entity_id: sensor.kamera_kallare
    to: 'Offline'
  action:
    - service: notify.telegram
      data:
        target: !secret telegram_par_chat_id
        title: 'Varning'
        message: "Kameran i källaren är offline"

- alias: 'Batteristatus på netatmo'
  trigger:
    platform: state
    entity_id: sensor.netatmo_vardagsrummet_battery, sensor.netatmo_badrum_kallare_battery, sensor.netatmo_utomhus_battery, sensor.netatmo_regnmatare_battery
    to: 'Low'
  action:
    - service: notify.telegram
      data_template:
        target: !secret telegram_par_chat_id
        title: 'Varning'
        message: 'Sensor {{ trigger.to_state.attributes.friendly_name }} har lågt batteri'

- alias: 'baksida dörr notis'
  trigger:
    platform: state
    entity_id: binary_sensor.baksidadorr_sensor
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.device_tracker
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
  action:
    - service: notify.telegram
      data_template:
        target: !secret telegram_par_chat_id
        title: 'Varning'
        message: 'Baksida dörr öppnades och ingen av er är hemma vad jag kan se'

- alias: 'Baksida dörr öppen'
  trigger:
    - platform: state
      entity_id: group.device_tracker
      to: 'not_home'
    - platform: state
      entity_id: input_boolean.vacation_mode
      to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.baksidadorr_sensor
      state: 'on'
  action:
    - service: notify.telegram
      data_template:
        target: !secret telegram_par_chat_id
        title: 'Varning'
        message: 'Baksida dörr fortfarande öppen'

- alias: 'Lampa offline'
  trigger:
    platform: state
    entity_id: light.lampa_ytterdorren
    to: 'unavailable'
    for:
      minutes: 10
  action:
    - service: notify.telegram
      data_template:
        target: !secret telegram_par_chat_id
        title: 'Varning'
        message: "{{ trigger.to_state.attributes.friendly_name }} är otillgänglig. Någon kanske trycke på knappen?"


- alias: 'God morgon'
  trigger:
    platform: state
    entity_id: input_boolean.all_asleep
    to: 'off'
  action:
    - service: notify.telegram
      data:
        title: 'God morgon!'
        message: |
          Ännu en härlig dag att se fram emot.
          Prognos just nu:
          {{ states.weather.smhi_home.state }}
          Förväntad mängd regn:
          {{ states.weather.smhi_home.attributes.forecast[0].precipitation }} mm
          Förväntad lägsta temperatur idag:
          {{ states.weather.smhi_home.attributes.forecast[0].templow }} grader
          Temperaturen just nu:  {{ states.sensor.netatmo_utomhus_temperature.state_with_unit }}
          {% if states.sensor.netatmo_regnmatare_sum_rain_24.state|float > 0 %}
          Det har regnat {{ states.sensor.netatmo_regnmatare_sum_rain_24.state_with_unit }} sedan midnatt
          {% endif %}
    - service: switch.turn_on
      entity_id: switch.ikea_switch_2
    - service: light.turn_on
      data:
        entity_id: light.dimmer_2_level
        brightness: 120

- alias: "Tvätten klar"
  trigger:
    platform: state
    entity_id: binary_sensor.washing_machine
    to: 'off'
  action:
    - service: telegram_bot.send_message
      data_template:
        message: "tvätten är klar!"
        inline_keyboard:
          - "Påminn mig senare:/washing_reminder"