- alias: "Ny enhet hittad notis"
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    - service: notify.telegram
      data:
        target: !secret telegram_par_chat_id
        message: "Ny enhet spåras: {{ trigger.event.data }}"

- alias: "Baksida dörr öppen"
  trigger:
    - platform: state
      entity_id: group.family
      to: "not_home"
    - platform: state
      entity_id:
        - input_boolean.vacation_mode
        - input_boolean.all_asleep
  condition:
    - condition: state
      entity_id: binary_sensor.dorr_baksidan
      state: "on"
  action:
    - service: notify.telegram
      data_template:
        message: "Tänkte bara nämna att dörren till baksidan är fortfarande öppen"

- alias: "God morgon"
  trigger:
    platform: state
    entity_id: input_boolean.all_asleep
    to: "off"
  action:
    - service: notify.telegram
      data:
        title: "God morgon!"
        message: |
          Ännu en härlig dag att se fram emot.
          Vädret just nu:
          {{ states.weather.smhi_home.state }} {{ states.sensor.netatmo_solleftegatan_80_vardagsrummet_utomhus_temperature.state_with_unit }}
          {% if states.weather.smhi_home.attributes.forecast[0].precipitation|float > 0 %}
          Förväntad mängd regn idag:
          {{ states.weather.smhi_home.attributes.forecast[0].precipitation }} mm
          {% endif %}
          {% if states.sensor.netatmo_solleftegatan_80_vardagsrummet_regnmatare_rain.state|float > 0 %}
          Det har regnat {{ states.sensor.netatmo_solleftegatan_80_vardagsrummet_regnmatare_rain.state_with_unit }}
          {% endif %}

- alias: "Tvätten klar"
  trigger:
    platform: state
    entity_id: sensor.washing_machine
    from: "on"
    to: "standby"
  condition:
    - condition: state
      entity_id: group.family
      state: "home"
  action:
    - service: telegram_bot.send_message
      data:
        message: "tvätten är klar!"
        inline_keyboard:
          - "Påminn mig senare:/washing_reminder"
    - service: tts.google_translate_say
      entity_id: media_player.kok
      data:
        message: "Tvätten är klar!"

- alias: "Tvätten är fortfarande kvar"
  trigger:
    platform: state
    entity_id: sensor.washing_machine
    to: "standby"
    for:
      hours: 1
  action:
    - service: notify.telegram
      data:
        message: "Tvätten är fortfarande klar. Om den är urplockad har ni glömt stänga av maskinen"

- alias: "Dåligt väder"
  trigger:
    - platform: numeric_state
      entity_id: weather.smhi_home
      value_template: "{{ states.weather.smhi_home.attributes.forecast[1].precipitation|float }}"
      above: 0.0
  condition:
    - condition: state
      entity_id: group.family
      state: "home"
  action:
    - service: notify.telegram
      data:
        message: |
          Tänkte bara upplysa er om eventuell nederbörd imorgon.
          Prognos: {{ states.weather.smhi_home.attributes.forecast[1].condition }}
          Mängd: {{ states.weather.smhi_home.attributes.forecast[1].precipitation }} mm

- alias: Update Available Notification
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      to: "on"
  action:
    - service: notify.telegram
      data:
        target: !secret telegram_par_chat_id
        message: "New hass version available: {{ state_attr('binary_sensor.updater', 'newest_version') }}"

- alias: "leaving work"
  trigger:
    platform: zone
    entity_id: person.par
    zone: zone.par_jobb
    event: leave
  condition:
    condition: time
    after: "16:00"
  action:
    - service: notify.telegram
      data:
        message: |
          Tänkte bara säga att Pär lämnade jobbet precis. Förmodligen är han på väg hem!

- alias: "Glöm inte tvätten"
  trigger:
    - platform: state
      entity_id: group.family
      from: "home"
      to: "not_home"
    - platform: state
      entity_id: group.family
      from: "not_home"
      to: "home"
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id:
          - sensor.washing_machine
        state: "off"
  action:
    - service: notify.telegram
      data:
        message: |
          Vill bara påminna om att tvättmaskinen är fortfarande igång.

- alias: Barnvakt
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.rorelsesensor_overvaningen_occupancy
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.kids_asleep
      state: "on"
  action:
    - service: notify.telegram
      data:
        message: "Rörelse övervåningen. Ett barn kanske är vaken?"

- alias: "Ringklockan"
  trigger:
    - platform: event
      event_type: nest_event
      event_data:
        device_id: efff89e264a037b0981bd2ecdb78cdf6
        type: doorbell_chime
  condition:
    - condition: state
      entity_id: group.family
      state: "home"
  action:
    - service: notify.telegram
      data:
        title: motion detected
        message: front door motion detected
        target: !secret telegram_par_chat_id

- alias: "Notis om barnvaktläge"
  trigger:
    - platform: state
      entity_id: input_boolean.kids_asleep
  action:
    - service: tts.google_translate_say
      entity_id: media_player.kok
      data:
        message: "Barnvaktläge är nu {{ states.input_boolean.kids_asleep.state }}"
