- alias: 'Uppdatering av home assistant finns'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.pushover
    data:
      message: 'Ny version av HA finns'

- alias: 'Glömde låsa dörren notis'
  trigger:
    - platform: state
      entity_id: device_tracker.par_telefon
      from: 'home'
      to: 'not_home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: lock.ytterdorren
        state: 'unlocked'
      - condition: state
        entity_id: group.device_tracker
        state: 'not_home'
  action:
    - service: notify.html5
      data_template:
        message: 'Dörren är upplåst och ingen är hemma'
        target: "Pär telefon"
        data:
          tag: 'forgot-lock'
          actions:
            - action: 'lock_door'
              title: 'Lås dörren'

- alias: "Notifiera ifall dörren är upplåst när kodi spelar"
  trigger:
    - platform: state
      entity_id: media_player.kodi
      to: 'playing'
  condition:
    condition: state
    entity_id: lock.ytterdorren
    state: 'unlocked' 
  action:
    - service: notify.html5
      data:
        message: 'Dörren är upplåst. Du kanske vill låsa när du ska sitta i källaren'
        target: "Pär telefon"
        data:
          tag: 'forgot-lock'
          actions:
            - action: 'lock_door'
              title: 'Lås dörren'

- alias: "Brandlarmet notis"
  trigger:
    - platform: event
      event_type: signal_received
      event_data: {"entity_id": "sensor.brandvarnare_2_sensor_status"}
  action:
    - service: notify.html5
      data:
        message: 'Brandlarmet utlöst!'
    - service: notify.pushover
      data:
        message: 'Brandlarmet utlöst!'
    - service: notify.telegram
      data:
        message: "Verkar som brandlarmet har utlösts klockan {{ now().strftime('%H:%M') }}!"

- alias: "Rörelse i källaren"
  trigger:
    - platform: state
      entity_id: binary_sensor.basement_entry
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.device_tracker
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
  action:
    service: notify.pushover
    data:
      message: 'Rörelse upptäckt i källaringången'

- alias: "Ny enhet hittad notis"
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    - service: notify.pushover
      data:
        message: 'Ny enhet spåras'

- alias: "morgon notis"
  trigger:
    platform: time
    at: '07:30:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: group.device_tracker
        state: 'home'
  action:
    - service: notify.telegram
      data:
        title: 'God morgon'
        message: |
          Ännu en härlig dag att se fram emot.
          Vädret ser ut att bli:
          {{ states('sensor.pws_weather_1d_metric') }}
          {% if states.sensor.netatmo_regnmatare_sum_rain_24.state|float > 0 %}
          Det har regnat {{ states.sensor.netatmo_regnmatare_sum_rain_24.state_with_unit }} sedan midnatt
          {% endif %}

- alias: "Enhet offline"
  trigger:
    platform: state
    entity_id: sensor.kamera_kallare
    to: 'Offline'
  action:
    - service: notify.telegram
      data:
        title: 'Varning'
        message: "Kameran i källaren är offline"

- alias: 'Tänd lampor'
  trigger:
    platform: time
    at: '06:00:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: device_tracker.par_telefon
        state: 'home'
  action:
    - service: notify.html5
      data:
        message: 'Tänd lampor?'
        target: "Pär telefon"
        data:
          tag: 'light1'
          actions:
            - action: 'light_indoor'
              title: 'Ja'

- alias: 'Batteristatus på netatmo'
  trigger:
    platform: state
    entity_id: sensor.netatmo_vardagsrummet_battery, sensor.netatmo_badrum_kallare_battery, sensor.netatmo_utomhus_battery, sensor.netatmo_regnmatare_battery
    to: 'Low'
  action:
    - service: notify.telegram
      data_template:
        title: 'Varning'
        message: 'Sensor {{ trigger.to_state.attributes.friendly_name }} har lågt batteri'

- alias: 'baksida dörr notis'
  trigger:
    platform: state
    entity_id: binary_sensor.sensor
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.device_tracker
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
  action:
    - service: notify.telegram
      data_template:
        title: 'Varning'
        message: 'Baksida dörr öppnades och ingen av er är hemma vad jag kan se'

- alias: 'Baksida dörr öppen'
  trigger:
    platform: state
    entity_id: group.device_tracker
    to: 'not_home'
  condition:
    - condition: state
      entity_id: binary_sensor.sensor
      state: 'on'
  action:
    - service: notify.telegram
      data_template:
        title: 'Varning'
        message: 'Baksida dörr fortfarande öppen, men ingen av er är hemma längre'

- alias: 'Lampa offline'
  trigger:
    platform: state
    entity_id: light.lampa_ytterdorren
    to: 'unavailable'
  action:
    - service: notify.telegram
      data_template:
        title: 'Varning'
        message: "{{ trigger.to_state.attributes.friendly_name }} är otillgänglig. Någon kanske trycke på knappen?"
