- alias: "Brandlarmet notis"
  trigger:
    - platform: event
      event_type: signal_received
      event_data: {"entity_id": "sensor.brandvarnare_2_sensor_status"}
  action:
    - service: notify.html5
      data:
        message: 'Brandlarmet utlöst!'
    - service: notify.pushover
      data:
        message: 'Brandlarmet utlöst!'
    - service: notify.telegram
      data:
        message: "Verkar som brandlarmet har utlösts klockan {{ now().strftime('%H:%M') }}!"

- alias: "Ny enhet hittad notis"
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    - service: notify.telegram
      data_template:
        target: !secret telegram_par_chat_id
        message: "Ny enhet spåras: {{ trigger.event.data }}"

- alias: "Enhet offline"
  trigger:
    platform: state
    entity_id: sensor.kamera_kallare
    to: 'Offline'
  action:
    - service: notify.telegram
      data:
        target: !secret telegram_par_chat_id
        title: 'Varning'
        message: "Kameran i källaren är offline"

- alias: 'Batteristatus på netatmo'
  trigger:
    platform: state
    entity_id: sensor.netatmo_solleftegatan_80_vardagsrummet_battery, sensor.netatmo_solleftegatan_80_badrum_kallare_battery, sensor.netatmo_solleftegatan_80_utomhus_battery, sensor.netatmo_solleftegatan_80_regnmatare_battery
    to: 'Low'
  action:
    - service: notify.telegram
      data_template:
        target: !secret telegram_par_chat_id
        title: 'Varning'
        message: 'Sensor {{ trigger.to_state.attributes.friendly_name }} har lågt batteri'

- alias: 'Baksida dörr öppen'
  trigger:
    - platform: state
      entity_id: group.family
      to: 'not_home'
    - platform: state
      entity_id: input_boolean.vacation_mode
      to: 'on'
    - platform: state
      entity_id: input_boolean.all_asleep
      to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.baksidadorr_sensor
      state: 'on'
  action:
    - service: notify.telegram
      data_template:
        target: !secret telegram_par_chat_id
        title: 'Varning'
        message: 'Baksida dörr fortfarande öppen'


- alias: 'God morgon'
  trigger:
    platform: state
    entity_id: input_boolean.all_asleep
    to: 'off'
  action:
    - service: notify.telegram
      data:
        title: 'God morgon!'
        message: |
          Ännu en härlig dag att se fram emot.
          Prognos just nu:
          {{ states.weather.smhi_home.state }}
          {% if states.weather.smhi_home.attributes.forecast[0].precipitation|float > 0 %}
          Förväntad mängd regn idag:
          {{ states.weather.smhi_home.attributes.forecast[0].precipitation }} mm
          {% endif %}
          Temperaturen just nu: {{ states.sensor.netatmo_solleftegatan_80_utomhus_temperature.state_with_unit }}
          {% if states.sensor.netatmo_solleftegatan_80_regnmatare_sum_rain_24.state|float > 0 %}
          Det har regnat {{ states.sensor.netatmo_solleftegatan_80_regnmatare_sum_rain_24.state_with_unit }} sedan midnatt
          {% endif %}

- alias: "Tvätten klar"
  trigger:
    platform: state
    entity_id: sensor.washing_machine
    from: 'on'
    to: 'standby'
  action:
    - service: telegram_bot.send_message
      data_template:
        message: "tvätten är klar!"
        inline_keyboard:
          - "Påminn mig senare:/washing_reminder"

- alias: "Tvätten är fortfarande kvar"
  trigger:
    platform: state
    entity_id: sensor.washing_machine
    to: 'standby'
    for:
      hours: 1
  action:
    - service: notify.telegram
      data:
        message: "Tvätten är fortfarande klar. Om den är urplockad har ni glömt stänga av maskinen"

- alias: 'Väg dig påminnelse'
  trigger:
    platform: state
    entity_id: input_boolean.all_asleep
    to: 'off'
    for:
      minutes: 5
  condition:
    - condition: state
      entity_id: device_tracker.par_telefon
      state: "home"
  action:
    - service: notify.telegram
      data_template:
        target: !secret telegram_par_chat_id
        message: Glöm inte väga dig.

- alias: 'Dåligt väder'
  trigger:
    - platform: numeric_state
      entity_id: weather.smhi_home
      value_template: "{{ states.weather.smhi_home.attributes.forecast[1].precipitation|float }}"
      above: 0.0
  condition:
    - condition: state
      entity_id: group.family
      state: "home"
  action:
    - service: notify.telegram
      data:
        message: |
          Tänkte bara upplysa er om eventuell nederbörd imorgon.
          Prognos: {{ states.weather.smhi_home.attributes.forecast[1].condition }}
          Mängd: {{ states.weather.smhi_home.attributes.forecast[1].precipitation }} mm

- alias: Update Available Notification
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      to: 'on'
  action:
    - service: notify.telegram
      data_template:
        target: !secret telegram_par_chat_id
        message: "New hass version available: {{ state_attr('binary_sensor.updater', 'newest_version') }}"

- alias: "leaving work"
  trigger:
    platform: zone
    entity_id: person.par
    zone: zone.par_jobb
    event: leave
  condition:
      condition: time
      after: '16:00'
  action:
    - service: notify.telegram
      data:
        message: |
          Tänkte bara säga att Pär lämnade jobbet precis. Förmodligen är han på väg hem!