- id: notify_open_door
  alias: "Dörr öppen notis"
  trigger:
    - platform: state
      entity_id: zone.home
      to: "0"

    - platform: state
      entity_id:
        - input_boolean.vacation_mode
        - input_boolean.all_asleep
      to: "on"
  action:
    - choose:
        - conditions:
            - condition: or
              conditions:
                - condition: state
                  entity_id: binary_sensor.sovrummet_contact
                  attribute: contact
                  state: open
                - condition: state
                  entity_id: binary_sensor.altandorren_contact
                  attribute: contact
                  state: open
          sequence:
            - service: notify.telegram
              data:
                title: "Dörr öppen"
                message: |
                  Följande dörr(ar) är öppna:
                  {% if is_state('binary_sensor.sovrummet_contact', 'open') %}
                    - Balkongdörren
                  {% endif %}
                  {% if is_state('binary_sensor.altandorren_contact', 'open') %}
                    - Altandörren
                  {% endif %}

- alias: "Tvätten klar"
  trigger:
    platform: state
    entity_id: sensor.washing_machine
    from: "on"
    to: "standby"
  condition:
    - condition: numeric_state
      entity_id:
        - zone.home
      above: "0"
  action:
    - service: notify.telegram
      data:
        message: |
          Tvätten är klar!
    - action: tts.speak
      target:
        entity_id: tts.google_translate_sv_se
      data:
        cache: true
        media_player_entity_id: media_player.kok
        message: "Tvätten är klar!"

- alias: "Tvätten är fortfarande kvar"
  trigger:
    platform: state
    entity_id: sensor.washing_machine
    from: "on"
    to: "standby"
    for:
      hours: 1
  action:
    - service: notify.telegram
      data:
        message: "Tvätten är fortfarande klar. Om den är urplockad har ni glömt stänga av maskinen"

- alias: Update Available Notification
  trigger:
    - platform: state
      entity_id: binary_sensor.home_assistant_website_update_available
      from: "off"
      to: "on"
  action:
    - service: notify.mobile_app_pixel_6_pro
      data:
        message: |
          Ny hass version: {{ states.sensor.home_assistant_website.state }}
          {{ states.sensor.home_assistant_website.attributes.release_notes }}

- alias: "leaving work"
  trigger:
    platform: zone
    entity_id: person.par
    zone: zone.par_jobb
    event: leave
  condition:
    condition: time
    after: "16:00"
  action:
    - service: notify.telegram
      data:
        message: |
          Tänkte bara säga att Pär lämnade jobbet precis. Förmodligen är han på väg hem!

- alias: "Glöm inte tvätten"
  trigger:
    - platform: state
      entity_id: zone.home
      to: "0"
    - platform: numeric_state
      entity_id: zone.home
      above: "0"
    - platform: state
      entity_id:
        - input_boolean.guest_mode
        - input_boolean.vacation_mode
      from: "off"
      to: "on"
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id:
          - sensor.washing_machine
        state: "off"
  action:
    - service: notify.telegram
      data:
        message: |
          Vill bara påminna om att tvättmaskinen är fortfarande igång.

- id: notify_kids_awake
  alias: "Barnvakts notis"
  trigger:
    - platform: state
      entity_id: binary_sensor.rorelsesensor_overvaningen_occupancy
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.barnvaktslage
      state: "on"
  action:
    - service: notify.telegram
      data:
        message: "Barn är vaken!"
        target: !secret telegram_par_chat_id
    - service: tts.speak
      target:
        entity_id: tts.google_translate_sv_se
      data:
        cache: true
        media_player_entity_id: media_player.biorummet
        message: "Barn är vaken!"
