- alias: 'Aktivera larmet'
  trigger:
    - platform: state
      entity_id: group.family
      to: not_home
      for:
        minutes: 10
    - platform: state
      entity_id: input_boolean.all_asleep
      to: 'on'
  action:
    - choose:
      - conditions:
          condition: not
          conditions:
            - condition: state
              entity_id:
                - group.family
              state: "home"
            - condition: state
              entity_id:
                - alarm_control_panel.ha_alarm
              state: armed
        sequence:
          - service: homeassistant.turn_off
            entity_id: group.indoor_lights
          - service: alarm_control_panel.alarm_arm_away
            entity_id: alarm_control_panel.ha_alarm
      - conditions:
          condition: not
          conditions:
            - condition: state
              entity_id:
                - input_boolean.all_asleep
              state: "off"
            - condition: state
              entity_id:
                - alarm_control_panel.ha_alarm
              state: armed
        sequence:
          - service: homeassistant.turn_off
            entity_id: group.indoor_lights
          - service: alarm_control_panel.alarm_arm_home
            entity_id: alarm_control_panel.ha_alarm


- alias: 'Deaktivera larmet'
  trigger:
    - platform: state
      entity_id: group.family
      to: home
    - platform: state
      entity_id: input_boolean.all_asleep
      to: 'off'
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: disarmed
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.telegram
      data_template:
        target: !secret telegram_par_chat_id
        title: 'Deaktiverar larmet'
        message: "Deaktiverat klockan {{ now().strftime('%H:%M') }} av `{{ trigger.entity_id }}`"

- alias: 'Sätt rörelse till av i källaren'
  trigger:
    - platform: state
      entity_id: binary_sensor.basement_entry
      to: 'on'
      for:
        minutes: 5
  action:
    service: mqtt.publish
    data:
        topic: 'emqtt/noreplypeers.se'
        payload: 'OFF'

- alias: 'Trigga larmet i bortaläge'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.baksidadorr_sensor
        - binary_sensor.mainfloor_movement
        - binary_sensor.basement_entry
        - binary_sensor.philips_hue_1_motion
      to: 'on'
    - platform: state
      entity_id: lock.ytterdorren
      to: 'unlocked'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    - service: input_text.set_value
      data_template:
        entity_id: input_text.triggered_alarm_entities
        value: "{{ trigger.entity_id }}"

- alias: 'Trigga larmet i hemmaläge'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.baksidadorr_sensor
        - binary_sensor.basement_entry
      to: 'on'
    - platform: state
      entity_id: lock.ytterdorren
      to: 'unlocked'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_home
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    - service: input_text.set_value
      data_template:
        entity_id: input_text.triggered_alarm_entities
        value: "{{ trigger.entity_id }}"

- alias: 'Skicka notis när larmet triggas'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: 'triggered'
  action:
    - service: notify.telegram
      data_template:
        target: !secret telegram_par_chat_id
        title: "ALARM!"
        message: "Larmet utlöst! Klockan {{ now().strftime('%H:%M') }}. Triggat av `{{ states('input_text.triggered_alarm_entities') }}`"
    - service: input_text.set_value
      data:
        entity_id: input_text.triggered_alarm_entities
        value: ''

- alias: 'Lås dörren automatiskt'
  trigger:
    - platform: state
      entity_id: group.family
      to: 'not_home'
      for:
        minutes: 5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: lock.ytterdorren
        state: 'unlocked'
  action:
    - service: lock.lock
      entity_id: lock.ytterdorren
    - service: notify.telegram
      data_template:
        title: 'Dörren låst'
        message: 'Jag låste dörren för ni är inte hemma längre'

