- id: security_activate_alarm
  alias: "Aktivera larmet"
  trigger:
    - platform: state
      entity_id: zone.home
      to: "0"
    - platform: state
      entity_id: input_boolean.all_asleep
      to: "on"
  action:
    - choose:
        - conditions:
            condition: not
            conditions:
              - condition: numeric_state
                entity_id:
                  - zone.home
                above: "0"
              - condition: state
                entity_id:
                  - alarm_control_panel.ha_alarm
                state: armed
          sequence:
            - service: light.turn_off
              entity_id:
                - light.inomhus
            - service: lock.lock
              entity_id:
                - lock.ytterdorren
            - service: alarm_control_panel.alarm_arm_away
              entity_id: alarm_control_panel.ha_alarm

        - conditions:
            condition: not
            conditions:
              - condition: state
                entity_id:
                  - input_boolean.all_asleep
                state: "off"
              - condition: state
                entity_id:
                  - alarm_control_panel.ha_alarm
                state: armed
          sequence:
            - service: light.turn_off
              entity_id:
                - light.inomhus
            - service: lock.lock
              entity_id:
                - lock.ytterdorren
            - service: alarm_control_panel.alarm_arm_home
              entity_id: alarm_control_panel.ha_alarm

- id: security_deactivate_alarm
  alias: "Deaktivera larmet"
  trigger:
    - platform: numeric_state
      entity_id: zone.home
      above: "0"
    - platform: state
      entity_id: input_boolean.all_asleep
      from: "on"
      to: "off"
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: disarmed
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.telegram
      data:
        target: !secret telegram_par_chat_id
        title: "Deaktiverar larmet"
        message: "Deaktiverat klockan {{ now().strftime('%H:%M') }} av `{{ trigger.entity_id }}`"

- id: security_trigger_alarm
  alias: "Trigga larmet i bortaläge"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.altandorren_contact
        - binary_sensor.mainfloor_movement
        - binary_sensor.rorelsesensor_overvaningen_occupancy
        - binary_sensor.rorelse_biorummet_occupancy
        - binary_sensor.balkongdorr_contact
      to: "on"
    - platform: state
      entity_id: lock.ytterdorren
      from: "locked"
      to: "unlocked"
    - platform: state
      entity_id:
        - camera.basement
        - camera.uvc_g3_flex
      from: "idle"
      to: "recording"
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    - service: input_text.set_value
      data:
        entity_id: input_text.triggered_alarm_entities
        value: "{{ trigger.entity_id }}"

- alias: "Trigga larmet i hemmaläge"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.altandorren_contact
      from: "off"
      to: "on"
    - platform: state
      entity_id: lock.ytterdorren
      from: "locked"
      to: "unlocked"
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_home
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    - service: input_text.set_value
      data:
        entity_id: input_text.triggered_alarm_entities
        value: "{{ trigger.entity_id }}"

- id: security_notify_alarm
  alias: "Skicka notis när larmet triggas"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      from:
        - armed_away
        - armed_home
      to: "triggered"
  action:
    - service: notify.telegram
      data:
        target: !secret telegram_par_chat_id
        title: "ALARM!"
        message: "Larmet utlöst! Klockan {{ now().strftime('%H:%M') }}. Triggat av `{{ states('input_text.triggered_alarm_entities') }}`"
    - service: input_text.set_value
      data:
        entity_id: input_text.triggered_alarm_entities
        value: ""
