- alias: 'Aktivera larmet när ingen är hemma'
  trigger:
    - platform: state
      entity_id: group.family
      to: not_home
      for:
        minutes: 10
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: disarmed
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.telegram
      data:
        target: !secret telegram_par_chat_id
        title: 'Aktiverar larmet'
        message: "Ingen hemma sedan 10 minuter tillbaka klockan {{ now().strftime('%H:%M') }}"

- alias: 'Deaktivera larmet när någon är hemma'
  trigger:
    - platform: state
      entity_id: group.family
      to: home
  condition: 
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_arm_home
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.telegram
      data:
        target: !secret telegram_par_chat_id
        title: 'Deaktiverar larmet'
        message: "Deaktiverat av att någon är hemma klockan  {{ now().strftime('%H:%M') }}"

- alias: 'Sätt rörelse till av i källaren'
  trigger:
    - platform: state
      entity_id: binary_sensor.basement_entry
      to: 'on'
      for:
        minutes: 5
  action:
    service: mqtt.publish
    data:
        topic: 'emqtt/noreplypeers.se'
        payload: 'OFF'

- alias: 'Trigga larmet när det är larmat'
  trigger:
    - platform: state
      entity_id: binary_sensor.baksidadorr_sensor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.mainfloor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.basement_entry
      to: 'on'
    - platform: state
      entity_id: lock.ytterdorren
      to: 'unlocked'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.ha_alarm

- alias: 'Skicka notis när larmet triggas'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: 'triggered'
  action:
    - service: notify.telegram
      data:
        target: !secret telegram_par_chat_id
        title: "ALARM!"
        message: "Larmet utlöst! Klockan {{ now().strftime('%H:%M') }}"

- alias: 'Lås dörren automatiskt'
  trigger:
    - platform: state
      entity_id: group.family
      to: 'not_home'
      for:
        minutes: 5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: lock.ytterdorren
        state: 'unlocked'
  action:
    - service: lock.lock
      entity_id: lock.ytterdorren
    - service: notify.telegram
      data_template:
        title: 'Dörren låst'
        message: 'Jag låste dörren för ni är inte hemma längre'
