- alias: "Starta luftfuktaren i barnrummet"
  trigger:
    platform: time_pattern
    minutes: 5
  condition:
    - condition: time
      after: '18:00:00'
      before: '07:00:00'
    - condition: numeric_state
      entity_id: sensor.netatmo_barnrummet_humidity
      below: 40
  action:
    - service: switch.turn_on
      entity_id: switch.ikea_switch_1

- alias: "Stoppa luftfuktaren i barnrummet"
  trigger:
    - platform: numeric_state
      entity_id: sensor.netatmo_barnrummet_humidity
      above: 50
    - platform: time
      at: '07:00:00'
  action:
    - service: switch.turn_off
      entity_id: switch.ikea_switch_1

- alias: "Tänd nattljus i barnens rum"
  trigger:
    platform: time
    at: '22:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.light_2
        color_name: red
        brightness: 50

- alias: "Släck nattljus i barnens rum"
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service: light.turn_off
      data:
        entity_id: light.light_2