- alias: "Starta luftfuktaren i barnrummet"
  trigger:
    platform: numeric_state
    entity_id: sensor.netatmo_barnrummet_humidity
    below: 40
    for:
      minutes: 10
  action:
    - service: switch.turn_on
      entity_id: switch.strombrytare_3

- alias: "Stoppa luftfuktaren i barnrummet"
  trigger:
    platform: numeric_state
    entity_id: sensor.netatmo_barnrummet_humidity
    above: 50
  action:
    - service: switch.turn_off
      entity_id: switch.strombrytare_3