- alias: "Tänd nattljus i barnens rum"
  trigger:
    - platform: time
      at: "22:00:00"
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control
        event: 2002
  condition:
    - condition: state
      entity_id: input_boolean.kids_away
      state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.light_2
          - light.samuels_nattlampa
        color_name: red
        brightness: 50

- alias: "Släck nattljus i barnens rum"
  trigger:
    platform: time
    at: "07:00:00"
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.light_2
          - light.samuels_nattlampa
